# Generated by Django 3.0.7 on 2020-06-10 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 18, 25, 16, 255198, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
