# Generated by Django 3.0.7 on 2020-06-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
    ]
